shopnet/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include(("users.urls", "users"), namespace="users"))

]

users/urls.py
# Django
from django.urls import path

# Vistas
from users.views import UserListView, UserAddView, UserDetailView, delete_user

urlpatterns = [
    path(
        route="list/",
        view=UserListView.as_view(),
        name="list"
    ),
    path(
        route="add/",
        view=UserAddView.as_view(),
        name="add"
    ),
    path(
        route="<int:pk>/",
        view=UserDetailView.as_view(),
        name="detail"
    ),
    path(
        route="delete/",
        view=delete_user,
        name="delete"
    )
]

users/models.py
# Django
from django.db import models

class Profile(models.Model):
    # Modelo del Perfil que amplía la información del Usuario de Django

    name = models.CharField(max_length=255)
    email = models.EmailField()
    age = models.PositiveIntegerField()
    job_title = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)

    def __str__(self):
        # Retorna el username
        return self.name

users/forms.py
# Django
from django import forms

# Models
from users.models import Profile

class ProfileForm(forms.ModelForm):
    # Model form del Profile
    class Meta:
        # Configuración del Form
        model = Profile
        fields = ("name", "email", "age", "job_title", "company_name")

users/views.py
# Django
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView

# Forms
from users.forms import ProfileForm

# Models
from users.models import Profile

class UserListView(ListView):

    template_name = "list.html"
    model = Profile
    ordering = ("id")
    paginate_by = 1000
    context_object_name = "users"


class UserAddView(CreateView):

    template_name = 'add.html'
    form_class = ProfileForm

    def get_success_url(self):
        # Redirecciona a la vista para listar los usuarios
        return reverse_lazy("users:list")

class UserDetailView(DetailView, UpdateView):
    template_name = "detail.html"
    slug_field = "username"
    slug_url_kwarg = "user"
    queryset = Profile.objects.all()
    context_object_name = "user"
    model = Profile
    fields = ["name", "email", "age", "job_title", "company_name"]
    
    def get_success_url(self):
        # Retorna la página del perfil de usuario
        return reverse('users:list')

def delete_user(request):
    if request.method =="POST":
        my_profile = Profile.objects.get(pk=request.POST.get("profile_pk"))
        my_profile.delete()
        return redirect("users:list")
    return redirect("users:list")

templates/add.html
{% extends "base.html" %}

{% block head_content %}

    {% load static %}
    <link rel="stylesheet" href="{% static "css/add.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

    <title>Shopnet</title>
<!--https://cssgradient.io/gradient-backgrounds/    Es la url para colores y diseños de gradiente-->
{% endblock  %}

{% block container %}

    <section class="add">
        <section class="add__container">
            <h2>Add User</h2>

            <form class="live__container--form" id="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                {{form.errors}}
                
                <div class="text">
                    <input class="input" type="text" name="name" value="" placeholder="Name"/>
                </div>

                <div class="text">
                    <input class="input2" type="email" name="email" value="" placeholder="Email"/>
                    <input class="input2" type="number" name="age" value="" placeholder="Age"/>
                </div>
                
                <div class="text">
                    <input class="input2" type="text" name="job_title" value="" placeholder="Job Title"/>
                    <input class="input2" type="text" name="company_name" value="" placeholder="Company"/>
                </div>
                
                <div class="button__container">
            
                    <label>
                        <button class="button2" type="submit" id="btn">Continue</button>  
                    </label>     
                </div>
            
            </form>

        </section>
    </section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block head_content %}{% endblock %}
    
</head>
<body>
    {% include "nav.html" %}

    {% block container %}
    {% endblock%}

</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block head_content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    <title>Shopnet</title>
{% endblock  %}

{% block container %}

    <section class="edit">
        <section class="edit__container">
            
            <form class="live__container--form" action="{% url "users:detail" user.pk %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.errors}}

                <div class="user_name">
                    <h4>Name</h4>
                    <input class="input" type="text" name="name" value="{{user.name}}">
                </div>

                <div class="user_name">
                    <h4>Email</h4>
                    <input class="input" type="email" name="email" value="{{user.email}}">
                </div>

                <div class="user_name">
                    <h4>Age</h4>
                    <input class="input" type="number" name="age" value="{{user.age}}">
                </div>                

                <div class="user_name">
                    <h4>Job Title</h4>
                    <input class="input" type="text" name="job_title" value="{{user.job_title}}">
                </div>

                <div class="user_name">
                    <h4>Company Name</h4>
                    <input class="input" type="text" name="company_name" value="{{user.company_name}}">
                </div>

                <div class="button__container">

                    <label>
                        <button class="button2" type="submit" name="enviar" value="Enviar" id="btn">Save User</button>
                    </label>     
                </div>
            </form>
            <form action="{% url "users:delete" %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{user.pk}}">
                <button class="button" type="submit">Delete User</button>
            </form>
        </section>
    </section>

{% endblock  %}

templates/list.html
{% extends "base.html" %}

{% block head_content %}

    {% load static %}
    <link rel="stylesheet" href="{% static "css/list.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

    <title>Shopnet</title>
<!--https://cssgradient.io/gradient-backgrounds/    Es la url para colores y diseños de gradiente-->
{% endblock  %}

{% block container %}

    <h2 class="user">Users List</h2>    
 
    <table style="width: 30%">
            {% for user in users %}

            <tr>
                <td>{{user.id}}</td>
                <td>{{user.name}}</td>
                <td>{{user.job_title}}</td>
            </tr>
            
            {% endfor %}
    </table>


{% endblock %}

templates/nav.html
<header class="header">
    {% load static %}
    <h1>SHOPNET</h1>
    <div class="header__menu">
        <div class="header__menu--profile">
            <img src="{% static 'images/usuario.png' %}" alt="">
        </div>
            <ul>
                <li><a href="{% url 'users:list' %}">Users List</a></li>
                <li><a href="{% url 'users:add' %}">Add User</a></li>
            </ul>
    </div>
</header>